---
### Consul template configuration
- name: Ensure all template files have been transferred on target host
  copy:
    src: "{{ item.src }}"
    dest: "{{ consul_template_data_path }}/{{ item.dest_filename }}"
    owner: "{{ consul_template_user }}"
    group: "{{ consul_template_group }}"
    mode: 0644
  loop: "{{ consul_template_files }}"
  notify:
    - restart consul-template

- name: Consul template configuration
  template:
    src: config.hcl.j2
    dest: "{{ consul_template_config_path }}/{{ consul_template_config_filename }}"
    owner: "{{ consul_template_user }}"
    group: "{{ consul_template_group }}"
    mode: 0644
  notify:
    - restart consul-template

- name: Ensure health check scripts has been transferred to the host
  copy:
    src: "files/{{ item }}"
    dest: "{{ consul_template_data_path }}/{{ item }}"
    owner: "{{ consul_template_user }}"
    group: "{{ consul_template_group }}"
    mode: 0644
  loop: "{{ health_checks_scripts }}"