---
### Consul template configuration
- name: Consul template configuration
  template:
    src: config.hcl.j2
    dest: "{{ consul_template_config_path }}/{{ consul_template_config_filename }}"
    owner: "{{ consul_template_user }}"
    group: "{{ consul_template_group }}"
    mode: 0644
  notify:
    - restart consul template
