---
# tasks file for ansible-consul-template
- name: Check requirements
  include: asserts.yml

- name: Include OS variables
  include_vars: "{{ ansible_os_family }}.yml"

- name: Include consul installation tasks for Debian
  include: "install_{{ ansible_os_family }}.yml"

#- name: Include consul configurations tasks
#  include: configure.yml
