---
# Add group
- name: Add Consul template group
  group:
    name: "{{ consul_template_group }}"
    state: present

# Add user
- name: Add Consul template user
  user:
    name: "{{ consul_template_user }}"
    comment: "Consul template user"
    group: "{{ consul_template_group }}"
    system: true
